### ISSUE TITLE
Contributorship Agreement

### ISSUE THREAD

**Issue by troettge** [troettge/Transparency-Ling#13]

**Comment by doomlab** [comment]
Alright team, I've put together the first draft of the agreement, which you can find [HERE](https://docs.google.com/document/d/1m2rFG9ccRyKizgFLMSLlYhrDApvkvMiqpezzSZnBzDM/edit?usp=sharing). The draft is editable, so please propose edits and comments as part of the discussion. After the team has agreed upon the draft, I'll put it in as part of the README for this project.

**Comment by troettge** [comment]
Made one comment, but overall, the draft sounds good to me!

**Comment by troettge** [comment]
@doomlab as far as I understood, we are all happy with it, so it can go into our read me file!

**Comment by doomlab** [comment]
Done! Closing this issue.
