### ISSUE TITLE
Notes for analysis

### ISSUE THREAD

**Issue by troettge** [troettge/Transparency-Ling#26]
- first 30 entries of form are pilot data and need to excluded (double check date)
- first few entries might have skipped the replication questions
- accidentally coded "Integration in two-way immersion education: Equalising linguistic benefits for all students" (0e3e42b8) as 64cf897b (coded at 12:27h on 1st Nov)
- when using Clarivate, journal titles are not stored with commas
- I did not consider additional methodological materials shared when they appear as appendix in the pdf of the paper

Need to double check:
- paper 0e08def6 is published online in 2010
- paper da673183 is published online  in 2017
- paper 096bc6a0 is published online  in 2016
- paper adb83706 is published online  in 2017
- paper 0d859c02 is published online  in 2017
- paper bf5f9a93 is published in 2021

**Comment by troettge** [comment]
double check JIF, when journal has no JIF, it shows the journal citation indicator (which looks very similar)

**Comment by LiamKeeble** [comment]
- I was unsure on whether to include papers on discourse analysis as an empirical study. I coded study types as `discourse analysis' so can exclude if necessary.
- I was also unsure on this front about a paper that included a few case studies. Coded study type as `case study', so can exclude if necessary.
- I also did not consider appendices in the pdf of papers as additional methodological materials shared.

**Comment by agboch** [comment]
Adding some of my comments:
- Article 13e813fe about animal communication (baboons) but with inferences about human language (lateralization) - exclude?
- I am coding most of the syntax analysis papers as typology (I think they are on the border of theoretical papers but frequently authors do collect data, e.g. by doing systematic searcher for their sentence examples online)
