### ISSUE TITLE
Recode 20% of articles

### ISSUE THREAD

**Issue by jvcasillas** [troettge/Transparency-Ling#27]
Here list of articles to recode. Like before, they are divided into sections, one for each coder (TR = Timo, JC = Joseph, LK = Liam, AB = Agata). Each item in the list contains the following information:

- Article ID: Random ID needed to input article information in google form
- Clickable DOI: Link for finding the article online
- Title of article: Title for searching if DOI fails
- Year split (Pre-OS, After-OS): If article is before or after OS (you can ignore this)
- Current coder initials: Double check the article is assigned to you

Note: There is a csv file `data > randomized_prescreen_df_rnd2_2022_03_14.csv` that includes who the previous coder was (will need for after)

# TR

- [x] f2e8b410, [doi](http://doi.org/10.1080/09500780903343070), Imagining higher education as a multilingual space, Pre-OS, tr
- [x] 0ddaefdf, [doi](http://doi.org/10.1017/S0047404509990443), Speaking beauties: Linguistic posturing, language inequality, and the construction of a Tanzanian beauty queen, Pre-OS, tr
- [x] 68eef7a5, [doi](http://doi.org/10.1177/0142723708091044), Conversational correlates of children's acquisition of mental verbs and a theory of mind, Pre-OS, tr
- [x] 15561653, [doi](http://doi.org/), Language and letters of the bluestocking network. Sociolinguistic issues in eighteenth-century epistolary English, Pre-OS, tr
- [x] 787d901e, [doi](http://doi.org/10.1097/01.TLD.0000333597.45715.57), Teaching graduate students to make evidence-based intervention decisions: Application of a seven-step process within an authentic learning context, Pre-OS, tr
- [x] 578b9ded, [doi](http://doi.org/10.1177/0033688209105866), A tale of two texts: Tracking developments in learner writing, Pre-OS, tr
- [x] cd4622f8, [doi](http://doi.org/10.1177/1461445608090225), Participation, procedure and accountability: 'You said'speech markers in negotiating reports of ambiguous phenomena, Pre-OS, tr
- [x] 91c8d5b5, [doi](http://doi.org/10.1080/13825570802151389), Coherence in translated television commercials, Pre-OS, tr
- [x] 82e85e07, [doi](http://doi.org/10.1177/0265532207083748), Issues and trends in language testing and assessment in Thailand, Pre-OS, tr
- [x] ca78d5c0, [doi](http://doi.org/10.1016/j.jneuroling.2009.06.004), Automatic processing of wh- and NP-movement in agrammatic aphasia: Evidence from eyetracking, Pre-OS, tr
- [x] 9e72d433, [doi](http://doi.org/10.1111/j.1749-818X.2007.00043.x), Islands, Pre-OS, tr
- [x] 4626f7e3, [doi](http://doi.org/10.1016/j.bandl.2009.03.001), The pars triangularis in dyslexia and ADHD: A comprehensive approach, Pre-OS, tr
- [x] 18902ff9, [doi](http://doi.org/10.1044/1092-4388(2009/07-0129)), The university college london archive of stuttered speech (UCLASS), Pre-OS, tr
- [x] 5918a6d7, [doi](http://doi.org/10.1007/s10849-008-9057-6), Notions of sameness by default and their application to anaphora, vagueness, and uncertain reasoning, Pre-OS, tr
- [x] 1d708c07, [doi](http://doi.org/10.1016/j.cognition.2008.09.006), A probabilistic corpus-based model of syntactic parallelism, Pre-OS, tr
- [x] 34bd38f5, [doi](http://doi.org/10.17576/3L-2018-2401-04), Influence of language learning anxiety on L2 speaking and writing of Filipino engineering students, After-OS, tr
- [x] 370493ca, [doi](http://doi.org/10.1016/j.lingua.2019.02.007), Home and away ‚Äì Implications of short-term sojourning of young Australian bilinguals, After-OS, tr
- [x] 3ed5f9b7, [doi](http://doi.org/10.1080/15235882.2019.1589604), Confronting ideologies: A discourse analysis of in-service teachers‚Äô translanguaging stance through an ecological lens, After-OS, tr
- [x] bfd89fc9, [doi](http://doi.org/10.1016/j.pragma.2017.06.013), Inviting in Mandarin: Anticipating the likelihood of the success of an invitation, After-OS, tr
- [x] d3ebac3a, [doi](http://doi.org/10.1007/s10936-018-9612-5), Predictive Language Processing in Preschool Children with Autism Spectrum Disorder: An Eye-Tracking Study, After-OS, tr
- [x] 8183a3b8, [doi](http://doi.org/10.1111/flan.12391), Exploring achievement goal theory, ACTFL's 5 Cs, and the L2 classroom: What goals do students set?, After-OS, tr
- [x] 8776f3ff, [doi](http://doi.org/10.1177/0033688217746205), Drama for L2 Speaking and Language Anxiety: Evidence from Brazilian EFL Learners, After-OS, tr
- [x] 4918b08b, [doi](http://doi.org/10.1515/sem-2016-0206), Translating iconicities of classical Chinese poetry, After-OS, tr
- [x] 69f774ea, [doi](http://doi.org/10.1093/elt/ccy061), Japanese student writers' perspectives on anonymous peer review, After-OS, tr
- [x] a1d6bec3, [doi](http://doi.org/), Constructing, reconstructing and developing teacher identity in supportive contexts, After-OS, tr
- [x] 659126a2, [doi](http://doi.org/10.1017/S136672891800055X), A Bayesian approach to establishing coreference in second language discourse: Evidence from implicit causality and consequentiality verbs, After-OS, tr
- [x] 5e0d1073, [doi](http://doi.org/), A quantitative lexical study on commercial english, After-OS, tr
- [x] 8328c7d1, [doi](http://doi.org/10.1002/tesj.415), Equal educational opportunity for English learners: ESL teachers‚Äô conceptualizations on the importance of academic language, After-OS, tr
- [x] 8c013c3c, [doi](http://doi.org/10.1016/j.wocn.2018.06.001), Using meta-analysis for evidence synthesis: The case of incomplete neutralization in German, After-OS, tr
- [x] 9555e6f3, [doi](http://doi.org/10.1017/S1366728918000858), Bilingualism as a desirable difficulty: Advantages in word learning depend on regulation of the dominant language, After-OS, tr

# JC

- [x] 6e7fcfb0, [doi](http://doi.org/10.2167/jmmd548.0), Classroom discourse and discursive practices in higher education in tanzania, Pre-OS, jc
- [x] fe59ac43, [doi](http://doi.org/10.1515/LITY.2009.005), On the (un)suitability of semantic categories, Pre-OS, jc
- [x] 09a75114, [doi](http://doi.org/10.1016/j.jcomdis.2007.10.003), University students' perceptions of pre-school and kindergarten children who stutter, Pre-OS, jc
- [x] fda28461, [doi](http://doi.org/10.1075/jlp.7.3.05kol), Semiotic and cognitive aspects of city branding, Pre-OS, jc
- [x] c86ce509, [doi](http://doi.org/10.7202/038907ar), Normalisation and the translation of phraseology in the COVALT corpus, Pre-OS, jc
- [x] 3d3e175d, [doi](http://doi.org/10.1080/02687030600927092), Testing single- and dual-route computational models of auditory repetition with new data from six aphasic patients, Pre-OS, jc
- [x] ccc62ae2, [doi](http://doi.org/10.1111/j.1467-971X.2009.01611.x), Thanking responders in Cameroon English, Pre-OS, jc
- [x] 2a118a86, [doi](http://doi.org/10.2478/v10057-008-0006-x), Cognitive and lexical characteristics of Motion in liquid medium: AQUA-motion verbs in typologically different languages, Pre-OS, jc
- [x] 140ff9b3, [doi](http://doi.org/10.7202/044782ar), Interpretation at the Tokyo War Crimes Tribunal: An overview and Tojo's cross-examination, Pre-OS, jc
- [x] 0a3fbaf7, [doi](http://doi.org/10.1515/COG.2008.002), In defence of iconicity, Pre-OS, jc
- [x] c7fc9c27, [doi](http://doi.org/10.1044/0161-1461(2008/009)), The impact of early intervention on speech and lexical development for toddlers with cleft palate: A retrospective look at outcome, Pre-OS, jc
- [x] ab568dcc, [doi](http://doi.org/10.1142/S1793351X09000902), Mapping verbal argument preferences to deverbal nouns, Pre-OS, jc
- [x] fff9fbc6, [doi](http://doi.org/), Language learning through tasks in a Content and Language Integrated Learning (CLIL) science classroom, Pre-OS, jc
- [x] 4fba2fe2, [doi](http://doi.org/10.1080/14992020801887786), FIST: A French sentence test for speech intelligibility in noise, Pre-OS, jc
- [x] 1a481136, [doi](http://doi.org/10.1086/604705), Two participles of the Carib language of Surinam, with their nominal, verbal, and adjectival properties, Pre-OS, jc
- [x] 4937a608, [doi](http://doi.org/10.1080/13488678.2018.1471639), Negotiating ‚Äòares,‚Äô ‚Äòcans,‚Äô and ‚Äòshoulds‚Äô of being and becoming in English language teaching: two teacher accounts from one Japanese university, After-OS, jc
- [x] 4c82f2bc, [doi](http://doi.org/10.1016/j.linged.2018.12.005), ‚ÄúI still think there's a need for proper, academic, Standard English‚Äù: Examining a teacher's negotiation of multiple language ideologies, After-OS, jc
- [x] d3efc028, [doi](http://doi.org/10.2989/16073614.2019.1692678), Passive and anticausative constructions: A new perspective to morphosyntax and lexical semantic interfaces, After-OS, jc
- [x] 584bac7f, [doi](http://doi.org/10.1111/1460-6984.12390), Effect of type of language therapy on expressive language skills in patients with post-stroke aphasia, After-OS, jc
- [x] b0e7d5b3, [doi](http://doi.org/10.1002/trtr.1809), Hip-Hop Early Literacy in K‚Äì1 Classrooms, After-OS, jc
- [x] 69d205e9, [doi](http://doi.org/10.1080/23273798.2017.1410560), Metaphoric extension, relational categories, and abstraction, After-OS, jc
- [x] db234c5c, [doi](http://doi.org/10.1007/s41701-017-0029-4), ‚ÄòWe Are Going to Do a Lot of Things for College Tuition‚Äô: Vague Language in the 2016 U.S. Presidential Debates, After-OS, jc
- [x] 51173c44, [doi](http://doi.org/10.22210/govor.2018.35.10), Synchronised and non-synchronised articulation of Polish nasals ƒÖ and ƒô in child and adult speech, After-OS, jc
- [x] fb7f587c, [doi](http://doi.org/10.1075/jhl.17014.lam), The replacement of diminutive suffixes in the New High German period: A time series analysis in word formation, After-OS, jc
- [x] 548f6c5a, [doi](http://doi.org/10.1080/14708477.2019.1569671), Exploring dialectal variations on quality health communication and healthcare delivery in the Sissala District of Ghana, After-OS, jc
- [x] 1bbe2aee, [doi](http://doi.org/10.1007/s10772-017-9481-6), Combining evidences from excitation source and vocal tract system features for Indian language identification using deep neural networks, After-OS, jc
- [x] c55bef99, [doi](http://doi.org/10.1002/trtr.1845), Language, Race, and Critical Conversations in a Primary-Grade Writers' Workshop, After-OS, jc
- [x] a265d9b5, [doi](http://doi.org/10.1017/S0142716419000018), Unraveling the complexity of the relations of metalinguistic skills to word reading with struggling adult readers: Shared, independent, and interactive effects, After-OS, jc
- [x] bc9c82ba, [doi](http://doi.org/10.1002/trtr.1693), The Uses and Misuses of Graphic Organizers in Content Area Learning, After-OS, jc
- [x] 2a8c4cf5, [doi](http://doi.org/10.1515/cllt-2016-0061), Similarity is closeness: Using distributional semantic spaces to model similarity in visual and linguistic metaphors, After-OS, jc

# LK

- [x] bf1f50fa, [doi](http://doi.org/10.1016/j.bandl.2008.01.002), Communicative impairment in traumatic brain injury: A complete pragmatic assessment, Pre-OS, lk
- [x] 63eb8491, [doi](http://doi.org/10.1016/j.system.2008.12.006), The relative effectiveness of different types of direct written corrective feedback, Pre-OS, lk
- [x] dc9bcac8, [doi](http://doi.org/10.1016/j.bandl.2007.11.004), How left inferior frontal cortex participates in syntactic processing: Evidence from aphasia, Pre-OS, lk
- [x] 30e21b3b, [doi](http://doi.org/10.1044/1092-4388(2008/046)), Is parent-child interaction therapy effective in reducing stuttering?, Pre-OS, lk
- [x] b99b7997, [doi](http://doi.org/10.1075/ijcl.14.3.01sco), In memory of Tim Johns, Pre-OS, lk
- [x] 58049d3a, [doi](http://doi.org/10.1177/0261927X07313656), The implicit meta-theory that has inspired and restricted LCM research: Why some studies were conducted but others not, Pre-OS, lk
- [x] 902a08b1, [doi](http://doi.org/10.1044/1092-4388(2008/08-0119)), Effects of loud and amplified speech on sentence and word intelligibility in Parkinson disease, Pre-OS, lk
- [x] bbe3b391, [doi](http://doi.org/10.1016/j.system.2007.10.006), The role of linguistic knowledge in word-meaning inferencing, Pre-OS, lk
- [x] 239b8bc4, [doi](http://doi.org/10.1075/babel.55.2.03zha), Social context and translation of public notices, Pre-OS, lk
- [x] 5b30f988, [doi](http://doi.org/10.2104/aral0924), A study of EL2 pilots' radio communication in the general aviation environment, Pre-OS, lk
- [x] 47b9d84d, [doi](http://doi.org/10.1556/SSlav.54.2009.2.3), True blue: On the syntax and connotations of colour and 'class membership' adjectives in Russian, Pre-OS, lk
- [x] 6d6220da, [doi](http://doi.org/10.1162/coli.07-056-R1-07-027), Algorithms for deterministic incremental dependency parsing, Pre-OS, lk
- [x] 09bff6f1, [doi](http://doi.org/10.1016/j.cognition.2007.11.009), Phonotactic probability influences speech production, Pre-OS, lk
- [x] 4e6a7a61, [doi](http://doi.org/), On the position of Gaulish within Celtic from the point of view of glottochronology, Pre-OS, lk
- [x] 04a09446, [doi](http://doi.org/10.1080/23273798.2017.1401101), The N400 as an index of lexical preactivation and its implications for prediction in language comprehension, After-OS, lk
- [x] 9f5836ec, [doi](http://doi.org/10.1016/j.linged.2018.12.003), Are females and males equitably represented? A study of early readers, After-OS, lk
- [x] 914047d6, [doi](http://doi.org/10.1016/j.wocn.2019.100935), Visible amplitude: Towards quantifying prominence in sign language, After-OS, lk
- [x] a4895415, [doi](http://doi.org/10.1080/00437956.2019.1567038), Reading the word in a foreign tongue: Islam‚Äôs scripture and non-Arab Muslims <sup>‚Ä†</sup>, After-OS, lk
- [x] e36ab195, [doi](http://doi.org/10.1007/s11049-018-9436-x), Definiteness determined by syntax: A case study in Tagalog, After-OS, lk
- [x] ceb0e434, [doi](http://doi.org/10.1016/j.pragma.2017.10.017), ‚ÄúWhat's it called in Norwegian?‚Äù Acquiring L2 vocabulary items in the workplace, After-OS, lk
- [x] 836dc5fa, [doi](http://doi.org/10.1016/j.lingua.2019.01.005), From visual perception to evidentiality: A functional empirical approach to se ve que in Spanish, After-OS, lk
- [x] 87700a27, [doi](http://doi.org/10.1186/s40862-018-0062-2), The effectiveness of L2 vocabulary instruction: a meta-analysis, After-OS, lk
- [x] 001719cf, [doi](http://doi.org/10.1075/lic.17007.mal), English presentative semantic patterns as seen through a parallel translation corpus, After-OS, lk
- [x] 030a348b, [doi](http://doi.org/10.1007/s11145-018-9837-6), The apple doesn‚Äôt fall from the tree: parents‚Äô reading-related knowledge and children‚Äôs reading outcomes, After-OS, lk
- [x] fd5b7ec5, [doi](http://doi.org/10.1080/23273798.2017.1404114), From words-as-mappings to words-as-cues: the role of language in semantic knowledge, After-OS, lk
- [x] ff2483c9, [doi](http://doi.org/), The rule of law and the threat of civil disobedience in hong kong: Metaphorical structures in local media coverage, After-OS, lk
- [x] 98963718, [doi](http://doi.org/10.1075/wll.00029.bur), Developing a unified orthography for Berawan: An endangered Bornean language, After-OS, lk
- [x] 4d8c4194, [doi](http://doi.org/10.3917/ls.165.0095), Language, communication, and the politics of hope: Solidarity and work in the Italian migration infrastructure, After-OS, lk
- [x] 93d54a22, [doi](http://doi.org/10.1080/14790718.2019.1632315), Multilingual boost vs. cognitive abilities: testing two theories of multilingual language learning in a primary school context, After-OS, lk
- [x] 5408749b, [doi](http://doi.org/10.37237/100402), Establishing online synchronous support for self-access language learning, After-OS, lk

# AB

- [x] ac4ee2fb, [doi](http://doi.org/10.1075/jlp.7.2.04hal), On the language of the Clinton-Dole presidential campaign debates: General tendencies and successful strategies, Pre-OS, ab
- [x] bd6141be, [doi](http://doi.org/10.1044/0161-1461(2008/07-0053)), Mexican American mothers of low and middle socioeconomic status: Communication behaviors and interactive strategies during shared book reading, Pre-OS, ab
- [x] 9e6b6a1a, [doi](http://doi.org/10.17239/l1esll-2008.08.01.03), \"Coming to know\": Weaving aboriginal and western science knowledge, language, and literacy into the science classroom, Pre-OS, ab
- [x] fcec4fcc, [doi](http://doi.org/), Constraint on covariation: It's not meaning, Pre-OS, ab
- [x] d256d617, [doi](http://doi.org/10.1016/j.jneuroling.2008.07.001), Knowledge of the semantic constraints on adjective order can be selectively impaired, Pre-OS, ab
- [x] 86897574, [doi](http://doi.org/10.1515/IJSL.2008.014), Morocco's languages and gender: Evidence from the field, Pre-OS, ab
- [x] 67e155b9, [doi](http://doi.org/10.1093/ijl/ecn021), The Lexis of electronic gaming on the Web: A sinclairian approach, Pre-OS, ab
- [x] b4634b48, [doi](http://doi.org/10.3176/lu.2008.2.04), A note on personal pronouns in Enets and Northern Samoyedic, Pre-OS, ab
- [x] d9c7a6c3, [doi](http://doi.org/10.1007/s11145-008-9138-6), Story writing skills of adults with a history language-impairment, Pre-OS, ab
- [x] f5dbe587, [doi](http://doi.org/10.1017/S026607840999040X), The ET Column: Thoughts from Kolkata on English in India, Pre-OS, ab
- [x] 795dfcd3, [doi](NA), Ironic openings: The interpretive challenge of the \Black Manifesto\" 2008 "Quarterly Journal of Speech, Pre-OS, ab
- [x] 005d3923, [doi](http://doi.org/10.1016/j.specom.2008.11.001), Charisma perception from text and speech, Pre-OS, ab
- [x] 0c7f90e8, [doi](http://doi.org/), Measuring and assessing the development of foreign language writing competence, Pre-OS, ab
- [x] b192ec7e, [doi](http://doi.org/), Taking a reading/writing intervention for secondary English language learners on the road: Lessons learned from the pathway project, Pre-OS, ab
- [x] 2bfa9134, [doi](http://doi.org/10.1017/S0142716409090237), Talking about writing: What we can learn from conversations between parents and their young children, Pre-OS, ab
- [x] a81616b9, [doi](http://doi.org/10.1353/lan.2018.0000), The lexicalist hypothesis: Both wrong and superfluous, After-OS, ab
- [x] 4b363385, [doi](http://doi.org/10.1353/jsl.2019.0003), The effects of animacy and givenness on object order in croatian child language, After-OS, ab
- [x] a584e7b1, [doi](http://doi.org/10.21315/kajh2018.25.1.2), The implication of conjunctive element shifts in the translation of argumentative texts, After-OS, ab
- [x] 5ff4ba27, [doi](http://doi.org/10.1163/15699846-01801005), Where does the modality of Ancient Greek modal verbs come from? the relation between modality and oblique case marking, After-OS, ab
- [x] aa0f2804, [doi](http://doi.org/10.1177/0033688217716507), Profiling Collocations in EFL Writing of Chinese Tertiary Learners, After-OS, ab
- [x] 204d833e, [doi](http://doi.org/10.22601/PET.2018.03.03), Positive and negative politeness in spoken lithuanian, After-OS, ab
- [x] 38c5c978, [doi](http://doi.org/10.1080/14708477.2018.1474887), Lobster, tourism and other kinds of business. Economic opportunity and language choice in a multilingual village in Belize, After-OS, ab
- [x] ec834df1, [doi](http://doi.org/10.1556/084.001), That again: A multivariate analysis of the factors conditioning syntactic explicitness in translated English, After-OS, ab
- [x] d3c6c187, [doi](http://doi.org/10.12963/csd.18572), Language familiarity hypothesis and delayed auditory feedback: A study on speech disruptions in typical Kannada (L1)-English (L2) bilinguals | Ïñ∏Ïñ¥ ÏπúÏàôÏÑ± Í∞ÄÏÑ§Í≥º ÏßÄÏó∞Ï≤≠Í∞ÅÏó≠ÏûÖ: Ïπ∏ÎÇòÎã§Ïñ¥(L1)-ÏòÅÏñ¥(L2) Ïù¥Ï§ëÏñ∏Ïñ¥ÏÇ¨Ïö© ÏùºÎ∞òÏïÑÎèôÏùò Íµ¨Ïñ¥Î∂ïÍ¥¥, After-OS, ab
- [x] ab11bec5, [doi](http://doi.org/10.1007/s10590-019-09229-6), Post-editing neural machine translation versus phrase-based machine translation for English‚ÄìChinese, After-OS, ab
- [x] 5c31bef1, [doi](http://doi.org/10.1080/09658416.2019.1636802), The construction of conflict talk across workplace contexts: (towards) a theory of conflictual compact, After-OS, ab
- [x] 4f6001c2, [doi](http://doi.org/10.1080/10573569.2018.1560379), Retention of Reading Intervention Effects From Fourth to Fifth Grade for Students With Reading Difficulties, After-OS, ab
- [x] 259ca9da, [doi](http://doi.org/10.1044/2019_JSLHR-S-18-0440), Vowel and tone identification for Mandarin congenital amusics: Effects of vowel type and semantic content, After-OS, ab
- [x] 7da82b85, [doi](http://doi.org/10.1515/ling-2019-0019), (Inter)subjective uses of the Dutch progressive constructions, After-OS, ab
- [x] 1deba029, [doi](http://doi.org/10.1016/j.system.2018.04.009), Collaborative writing in the EFL classroom: The effects of L1 and L2 use, After-OS, ab

**Comment by agboch** [comment]
Thanks @jvcasillas! I think I already see an article on my list that I already coded in primary coding (4c17af36, [doi](http://doi.org/10.1093/jss/fgp007), "On the Arabian origins of the Qur'ƒÅn: The case of al-furqƒÅn", Pre-OS, ab - it was from redistributed list from MR articles). Maybe you can double check if there are more like that?

**Comment by jvcasillas** [comment]
@troettge 
Here is a link to the zip file containing all articles: https://www.dropbox.com/s/h6itqxe1mry3z8s/yes.zip?dl=0

This should facilitate coder meetings regarding discrepancies.
