### ISSUE TITLE
Manuscript draft

### ISSUE THREAD

**Issue by agboch** [troettge/Transparency-Ling#28]
[Here ](https://docs.google.com/document/d/11XqcU-ukuZX3wt6J2w2tRgz6sy18xt-B4q0SuIBoWNY/edit?usp=sharing)is a google doc for drafting the manuscript.

**Comment by troettge** [comment]
Wrote a drafty draft. See what you think, folks! [Here](https://docs.google.com/document/d/11XqcU-ukuZX3wt6J2w2tRgz6sy18xt-B4q0SuIBoWNY/edit?usp=sharing)
