### ISSUE TITLE
Decide on sampling procedure

### ISSUE THREAD

**Issue by troettge** [troettge/Transparency-Ling#3]
See measured variables from [Hardwicke et al. (2021).](https://osf.io/q96eh/)

Sampling is done via [Scopus](https://www.scopus.com/) 

Following the psych journal (changed years to reflect two points in time (a) prior to replication crisis and (b) most recent).

- sourcetype: journal (j)
- document types: articles (ar) + review (re)
- publication year: 2008-2009 + 2018-2019
- language: English

suggestion for subject-terms following ASJC Code: 
- SUBJTERMS(1203) = Language and Linguistics
- SUBJTERMS(3310) = Linguistics and Language

Corresponds to Scopus query: 
SRCTYPE ( j ) AND ( SUBJTERMS ( 1203 ) OR SUBJTERMS ( 3310 ) ) AND ( LIMIT-TO ( DOCTYPE,"ar" ) OR LIMIT-TO ( DOCTYPE,"re" ) ) AND ( LIMIT-TO ( PUBYEAR,2008) OR LIMIT-TO ( PUBYEAR,2009) OR LIMIT-TO ( PUBYEAR,2018) OR LIMIT-TO ( PUBYEAR,2019) ) AND ( LIMIT-TO ( LANGUAGE,"English" ) )

A possible problem with this approach is that there are journals that clearly aren't linguistic (e.g. "Notes & Queries"). 

SOLUTION: Manually check paper and if not on language, then put back on "questionable" pile and cross-validate with someone else.

A possible opportunity for exploration comes with other the discipline codes. Our journals overlap with the following macro disciplines (top 5):
- Psychology (14%)
- Health Professions (9%)
- Computer Science (8%)
- Neuroscience (5%)
- Medicine (3%)

**Comment by melroethlisberger** [comment]
- Selection of documents to search for: OK
- Search query in scopus: OK, I tried it with the tools I had at hand, not using LIMIT-TO but just OR and AND: 

Query: SRCTYPE ( j )  AND  ( SUBJTERMS ( 1203 )  OR  SUBJTERMS ( 3310 ) )  AND  LANGUAGE ( english )  AND  ( PUBYEAR  =  2008  OR  PUBYEAR  =  2009  OR  PUBYEAR  =  2018  OR  PUBYEAR  =  2019 )  AND  ( DOCTYPE ( ar )  OR  DOCTYPE ( re ) )

= Same number: 48'066 results.

- Export: there is a maximum of 20'000 articles to be exported and only information on citation can be exported.
