### ISSUE TITLE
Zotero group library

### ISSUE THREAD

**Issue by jvcasillas** [troettge/Transparency-Ling#33]
I have created our group library. You should all be added and I imagine you will receive a notification. If not, it is because the email I have for you is not the same as the one you use with your zotero account (or you don't have a zotero account). I started our library, `Transparency-Ling` from a previous library (@troettge it's the MSA bib, minus all the stats stuff). I will add refs as I read/edit the manuscript. Feel free to add and edit as necessary and leave a comment here if you have any issues. You can get more information about how to use group libraries on zotero here: https://guides.library.oregonstate.edu/c.php?g=359201&p=2426111 

And I am going to tag everybody here in case you don't have notifications on for new issues. @doomlab @melroethlisberger @caitlin91 @LiamKeeble @agboch

**Comment by agboch** [comment]
@jvcasillas - doesn't seem like I have received your Zotero invitation, could you try to re-send it? (it's the same email as in our collab correspondence, in case my Zotero user here: https://www.zotero.org/agatabo)

**Comment by jvcasillas** [comment]
@agboch I tried again and it looks like it worked this time. Let me know if there are still problems.
