### ISSUE TITLE
Figure one suggestion

### ISSUE THREAD

**Issue by troettge** [troettge/Transparency-Ling#34]
- two different color schemes (still continuous but two discrete scales with so many categories is a clusterfuck), I can live with this design choice.
- changed orientation of legend and title so that the bars are right next to each other
- changed label color to increase contrasts relative to ground color.

![Rplot02](https://user-images.githubusercontent.com/13022447/186871273-dfa68c4d-631c-4875-ba4d-427b478ef044.png)

Design feedback (let's stick to user relevant feedback) here please until the 2nd of September. If you are okay with it post emoji  :shipit:

**Comment by jvcasillas** [comment]
This gets a :shipit: from me, but is there any reason you stuck with a continuous scale? Also, Southern Europe and Spanish being white is kind of funny to me.

**Comment by troettge** [comment]
pushed!

**Comment by troettge** [comment]
Completed
