### ISSUE TITLE
Set up google form for data collection

### ISSUE THREAD

**Issue by troettge** [troettge/Transparency-Ling#7]
pdf of their form [here](https://osf.io/x9rmy/)

**Comment by troettge** [comment]
Link to our form [here](https://forms.gle/VXe9VmZc4Giv5FNB6).

Comments on form, content, or structure in this issue.

**Comment by melroethlisberger** [comment]
1.3. I checked "article is not about language" but was still forwarded to the questions 2.1, etc.

**Comment by mahowak** [comment]
1.3 +1 for making it so we can skip right to end if questions not applicable or at least making all questions optional so that it is easy to skip through.
1.3 I had a paper which was about teaching English. The questions were about education, not language. So I considered that to be not about language but would be open to discussion. I also had an article which was a personal remembrance of Washoe, which I coded as not about language, but also open to disucssion.

**Comment by mahowak** [comment]
1.3 None of my 4 articles was the kind of scientific language paper of the sort I think we mostly imagine focusing on and that would benefit from this method. I wonder if it's worth thinking about picking a restricted set of journals to focus on, even if it means losing some breadth. Just skimming titles, we have a lot of education, poetics, translation, etc. (Education is a huge field so this is maybe not surprising.)

**Comment by troettge** [comment]
Open questions.

- How do we handle JIFs? JIFs are only available for the last 10 years (so 2008/09) are out. Possible solution: either take last available JIF or we only note down JIF at time of coding the article? (edit document
- How do we actually approach the OA question. Melanie made a good point: If we are in our Uni network and the Uni has a subscription, unpaywall will consider it as openaccess. Not being in our Uni network while coding strikes me as terrible inconvenient. Suggestions?

@LiamKeeble @mahowak @melroethlisberger @jvcasillas @caitlin91 @agboch @doomlab

**Comment by doomlab** [comment]
@troettge 
- Maybe just the JIF now? 
- I think we caveat the open access section by simply saying "we considered it 'open' if one of the research team could access it but the limitation to this system is paid university access may not be seen as completely open".
